console.log("js from Dev1");
console.log("red");
console.log("yeallow");
console.log("js from Dev1");
console.log("js from Dev1");
console.log("js from Dev2-->changes");
console.log("js from Dev2");
console.log("js from Dev3");
console.log("js from Dev2");
console.log("js from Dev2");
console.log("js from Dev3");
